add executable

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -131,6 +131,14 @@ jobs:
             echo "Running tests"
             cargo test --all -- --nocapture
 
+      - name: Copy known executable on failure for debugging
+        if: failure()
+        run: |
+          sudo chmod -R 777 /tmp/coredumps
+          mkdir -p /tmp/coredumps/executables
+          sudo chown $USER:$USER target/debug/deps/samples_echomain_stateful2-*
+          sudo cp target/debug/deps/samples_echomain_stateful2-* /tmp/coredumps/executables/ || { echo "Fail to copy known executable"; exit 1; }
+
       - name: Collect core dumps
         if: always()
         run: |
