Linux onebox ci stability (#263)
After linux onebox is changed to 5 nodes, it takes longer for it to be
ready, and system services takes longer to function. This caused higher
failure rate for our application creation setup.
This PR adds retries for the application setup script. The failure rate
is reduced to the previous 3 node cluster level.
Also apply the FabricClient drop hack to the aux replica test to avoid
known seg faults.

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -204,7 +204,7 @@ jobs:
             cmake . -DCMAKE_BUILD_TYPE=Debug -B build
             cmake --build build --config Debug
             echo "Preparing test apps"
-            bash ./scripts/prepare_test_apps.sh
+            bash ./scripts/prepare_test_apps.sh || { echo "Fail to prepare test apps"; exit 1; }
             echo "Running tests"
             cargo test --all -- --nocapture
 
