Enable core dumps in ci (#213)
Enables collecting core dumps for test crashes.
Onebox app dump collection will be added in a separate PR.

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -64,7 +64,6 @@ jobs:
     - name: Run cargo test
       run: cargo test --all -- --nocapture
 
-  # Do not run test because SF onebox is not supported on azl3 yet.
   build-azl3:
     runs-on: ubuntu-latest
     container:
@@ -113,6 +112,13 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v5
 
+      - name: Configure core dumps
+        run: |
+          mkdir -p /tmp/artifacts/coredumps
+          sudo chmod 777 /tmp/artifacts/coredumps
+          ulimit -c unlimited
+          echo "/tmp/artifacts/coredumps/core.%e.%p.%h.%t" | sudo tee /proc/sys/kernel/core_pattern
+
       - name: Run in Dev Container
         uses: devcontainers/ci@v0.3
         with:
@@ -124,3 +130,30 @@ jobs:
             bash ./scripts/prepare_test_apps.sh
             echo "Running tests"
             cargo test --all -- --nocapture
+
+      - name: Copy known executable on failure for debugging
+        if: failure()
+        run: |
+          mkdir -p /tmp/artifacts/executables
+          sudo chown $USER:$USER target/debug/deps/samples_echomain_stateful2-*
+          sudo cp target/debug/deps/samples_echomain_stateful2-* /tmp/artifacts/executables/ || { echo "Fail to copy known executable"; exit 1; }
+
+      - name: Collect core dumps
+        if: always()
+        run: |
+          echo "Collecting core dumps"
+          sudo chmod -R 777 /tmp/artifacts
+          if [ -d "/tmp/artifacts/coredumps" ] && [ "$(ls -A /tmp/artifacts/coredumps 2>/dev/null)" ]; then
+            tar -czf artifacts.tar.gz -C /tmp artifacts || { echo "Fail to archive core dumps"; exit 1; }
+            echo "Core dumps collected"
+          else
+            echo "No core dumps found"
+          fi
+
+      - name: Upload core dumps artifact if exists
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: artifacts-${{ matrix.devcontainer-type }}-run${{ github.run_id }}-attempt${{ github.run_attempt }}
+          path: artifacts.tar.gz
+          if-no-files-found: ignore
