Rename to Reflection app

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -93,7 +93,7 @@ jobs:
       run: |
         # The test will add and remove app
         .\tests\echo_script_test.ps1
-        .\scripts\echomain_stateful_ctl2.ps1 -Action Add
+        .\scripts\reflection_ctl.ps1 -Action Add
         .\scripts\echomain_ctl.ps1 -Action Add
 
     - name: Run cargo test
@@ -227,8 +227,8 @@ jobs:
         if: failure()
         run: |
           mkdir -p /tmp/artifacts/executables
-          sudo chown $USER:$USER target/debug/deps/samples_echomain_stateful2-*
-          sudo cp target/debug/deps/samples_echomain_stateful2-* /tmp/artifacts/executables/ || { echo "Fail to copy known executable"; exit 1; }
+          sudo chown $USER:$USER target/debug/deps/samples_reflection-*
+          sudo cp target/debug/deps/samples_reflection-* /tmp/artifacts/executables/ || { echo "Fail to copy known executable"; exit 1; }
 
       - name: Collect core dumps
         if: always()
